---
title: "poli170a"
author: "Kelly Gong"
date: "2024-05-31"
output:
  pdf_document:
    keep_tex: true
header-includes:
   - \usepackage{dcolumn}    
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(stats)
library(stargazer)
library(ggplot2)
```

```{r}
merged_df <- read_csv("/Users/kellygong/Downloads/merged_df.csv")

```
```{r}
# Fit the linear model with log-transformed variables
full_model <- lm(crime_density ~ alcohol_density + density, data=merged_df)

# Print the summary of the model
summary(full_model)
```

```{r, results='asis'}
stargazer(full_model,
          type = "latex",
          title = "Results",
          align = TRUE,
          covariate.labels = c("Alcohol Density", "Population Density"),
          dep.var.labels = "Crime Density",
          dep.var.caption = "Dependent Variable")
```

```{r}
p <- ggplot(merged_df, aes(x = alcohol_density, y = crime_density, color = density)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE, color = "red") + 
  labs(
    x = 'Alcohol License per capita',
    y = 'Crime Incidents per capita',
    title = 'Relationship Between Alcohol Licenses and Crime Rates per Capita',
    color = 'Population Density'
  ) +
  scale_color_gradient(low = "lightblue", high = "darkblue") +
  theme_minimal() +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 8),
    legend.key.size = unit(1.5, "lines")
  )

print(p)
ggsave("scatterplot_license_vs_crime_density.png", plot = p, dpi = 300)
```